version: 2 #version of CircleCI that
jobs:  #Each job represents a phase in your Build-Test-Deploy process
  build:
    working_directory: ~/src
    docker:
      - image: circleci/android:api-29-node #Android 9
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout  #checkout codebase
      - restore_cache: #Next we pull down the cache, if present. If this is your first run, or if you’ve changed either of your build.gradle file, this won’t do anything.
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
#      - run:
#          name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
#          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - save_cache: #will store the dependencies in order to speed things up for next time.
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}

      - run:
          name: Run Tests
          command: ./gradlew lint test

      - store_artifacts: #After we get result from ./gradlew lint test , we upload the build reports as job artifacts# for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: app/build/reports
          destination: reports

      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: app/build/test-results # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
