# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  before_all do |lane, options|
    @build_type = "Debug"
    if not options.empty?
      @build_type = options[:release] ? "Release" : "Debug"
    end
  end

  desc "Assemble Build"
  lane :assemble_build do |options|
    gradle(task: "assemble", build_type: @build_type)
  end

  desc "Assemble Test Application"
  lane :assemble_test_application do |options|
    gradle(task: "assemble", build_type: "#{@build_type}AndroidTest")
  end

  desc "Assemble Build and Test Application"
  lane :assemble do |options|
    assemble_build options
    assemble_test_application options
  end

  desc "Run unit tests"
  lane :unit_tests do |options|
    gradle(task: "test", build_type: @build_type)
  end


  desc "Run Sonarqube"
  lane :sonarqube_analysis do
      sonar(
       project_key: "YassinELhadedy_EcommerceProductApp",
       project_name: "EcommerceProductApp",
       sources_path: "src/main/java",
       sonar_organization: "yassinelhadedy",
       sonar_login: ENV['SONAR_TOKEN'],
       sonar_url: ENV['SONAR_HOST_URL']
     )
  end

  desc "Run instrumentation tests in Firebase Test Lab"
  lane :instrumentation_tests_testlab do
    assemble
    run_tests_firebase_testlab(
        project_id: "ecommerce-35eeb",
        devices: [
          {
            model: "LEO-BX9",
            version: "sawfish/26"
          }
        ])
  end

 desc "Submit a new Beta Build to Crashlytics"
  lane :deploy_to_crashlytics do
    assemble_build
    crashlytics
  end

  desc "Ecommerce app"
  lane :distribute do
    gradle(task: "clean assembleDebug")
    # build_android_app is a built-in fastlane action.
    firebase_app_distribution(
      app: ENV['FIREBASE_APP_ID'],
      groups: "android-QA",
      release_notes: "Fastlane Droid Release Notes Updated 1.0.0",
      firebase_cli_path: "/usr/local/bin/firebase",
      firebase_cli_token: ENV['FIREBASE_DIS_TOKEN_CLI']
     )
   end


  desc "Ecommerce app"
  lane :distribute_production_version do
    gradle(task: "clean assembleRelease")
    # build_android_app is a built-in fastlane action.
    firebase_app_distribution(
      app: ENV['FIREBASE_APP_ID'],
      groups: "android-QA",
      release_notes: "Fastlane Droid Release Notes Updated 1.0.0",
      firebase_cli_path: "/usr/local/bin/firebase",
      firebase_cli_token: ENV['FIREBASE_DIS_TOKEN_CLI']
     )
   end


  desc "Upload Apk to App Center"
  lane :deploy_to_appcenter do
    assemble
    appcenter_upload(
      api_token: "54756a2ac3f2cb0048169d4b4ae6acb7d5a68063",
      owner_name: "yassinelhadidy-gmail.com",
      owner_type: "user", # Default is user - set to organization for appcenter organizations
      app_name: "Jumia-App",
      file: $GRADLE_APK_OUTPUT_PATH,
      notify_testers: true # Set to false if you don't want to notify testers of your new release (default: `false`)
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy_to_play_store do
    assemble_build release:true
    upload_to_play_store
  end
end